services:
    my_user_provider:
        class: Bound\CoreBundle\Provider\FOSUBUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [ @service_container, @doctrine.orm.entity_manager, @fos_user.user_manager, {facebook: facebook_id, google: google_id}]

    bound.user_manager:
        class: Bound\CoreBundle\Manager\UserManager
        arguments: [ @service_container, @doctrine.orm.entity_manager ]

    bound.achievement_manager:
        class: Bound\CoreBundle\Manager\AchievementManager
        arguments: [ @service_container, @doctrine.orm.entity_manager ]

    bound.crew_manager:
        class: Bound\CoreBundle\Manager\CrewManager
        arguments: [ @service_container, @doctrine.orm.entity_manager ]

    bound.token_manager:
        class: Bound\CoreBundle\Manager\TokenManager
        arguments: [ @service_container, @doctrine.orm.entity_manager ]
