services:
    my_user_provider:
        class: Bound\CoreBundle\Provider\FOSUBUserProvider
        arguments: [ @service_container, @doctrine.orm.entity_manager, @fos_user.user_manager, {facebook: facebook_id, google: google_id}]


    bound.user_manager:
        class: Bound\CoreBundle\Manager\UserManager
        arguments: [ @service_container, @doctrine.orm.entity_manager ]

    bound.achievement_manager:
        class: Bound\CoreBundle\Manager\AchievementManager
        arguments: [ @service_container, @doctrine.orm.entity_manager ]

    bound.crew_manager:
        class: Bound\CoreBundle\Manager\CrewManager
        arguments: [ @service_container, @doctrine.orm.entity_manager ]

    bound.token_manager:
        class: Bound\CoreBundle\Manager\TokenManager
        arguments: [ @service_container, @doctrine.orm.entity_manager ]

    bound.notification_manager:
        class: Bound\CoreBundle\Manager\NotificationManager
        arguments: [ @service_container, @doctrine.orm.entity_manager ]


    bound.email_listener:
        class: Bound\CoreBundle\Listener\EmailListener
        arguments: [ @service_container ]

    bound.curl_listener:
        class: Bound\CoreBundle\Listener\CurlListener
        arguments: [ @service_container ]

    bound.achievement_listener:
        class: Bound\CoreBundle\Listener\AchievementListener
        arguments: [ @service_container, @doctrine.orm.entity_manager ]
