bound_backoffice_achievement_list:
    path:     /list
    defaults: { _controller: BoundBackOfficeBundle:Achievement:list }

bound_backoffice_achievement_detail:
    path:     /detail/{achievement}
    defaults: { _controller: BoundBackOfficeBundle:Achievement:detail }

bound_backoffice_achievement_create:
    path:     /create
    defaults: { _controller: BoundBackOfficeBundle:Achievement:create }

bound_backoffice_achievement_edit:
    path:     /edit/{achievement}
    defaults: { _controller: BoundBackOfficeBundle:Achievement:edit }

bound_backoffice_achievement_delete:
    path:     /delete/{achievement}
    defaults: { _controller: BoundBackOfficeBundle:Achievement:delete }
