filter:
    path: [desk/src/*]
    excluded_paths: [ 'desk/vendor/*', 'desk/samples/*' ]

before_commands:
    - cd desk/
    - composer self-update
    - composer install

tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, samples]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, samples]
