language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - cd desk/
  - composer self-update
  - composer install
  - composer update
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - php app/console doctrine:fixtures:load -n --env=test

matrix:
  include:
    - php: 5.3.3
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 5.6
      env: DEPENDENCIES='dev' SYMFONY_VERSION='2.8.*@dev'
    - php: 5.6
      env: SYMFONY_VERSION='2.3.*'
    - php: 5.6
      env: SYMFONY_VERSION='3.0.*@dev'

script:
  - phpunit -c app/

notifications:
  email:
    - pierrick.gicquelais@epitech.eu
