<?php

namespace Bound\CoreBundle\Entity;

/**
 * CrewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrewRepository extends \Doctrine\ORM\EntityRepository
{
}
