<?php
/**
 * @Author: gicque_p
 * @Date:   2015-11-27 14:55:40
 * @Last Modified by:   gicque_p
 * @Last Modified time: 2015-11-27 15:00:22
 */

namespace Bound\CoreBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}
