bound_backoffice_index:
    path:     /
    defaults: { _controller: BoundBackOfficeBundle:Default:index }

bound_backoffice_achievement_list:
    path:     /achievement/list
    defaults: { _controller: BoundBackOfficeBundle:Achievement:list }
