bound_front:
    resource: "@BoundFrontBundle/Resources/config/routing.yml"
    prefix:   /

bound_back_office:
    resource: "@BoundBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admin

bound_api:
    resource: "@BoundApiBundle/Resources/config/routing.yml"
    prefix:   /api

app:
    resource: "@BoundFrontBundle/Controller/"
    type:     annotation


#FOSRoutes
fos_user_registration_check_email:
    path:     /check-email
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }

fos_user_registration_confirm:
    path:     /confirm/{token}
    defaults: { _controller: FOSUserBundle:Registration:confirm }

fos_user_registration_confirmed:
    path:     /confirmed
    defaults: { _controller: FOSUserBundle:Registration:confirmed }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
