bound_backoffice_user_list:
    path:     /list
    defaults: { _controller: BoundBackOfficeBundle:User:list }

bound_backoffice_user_detail:
    path:     /detail/{user}
    defaults: { _controller: BoundBackOfficeBundle:User:detail }

bound_backoffice_user_create:
    path:     /create
    defaults: { _controller: BoundBackOfficeBundle:User:create }

bound_backoffice_user_edit:
    path:     /edit/{user}
    defaults: { _controller: BoundBackOfficeBundle:User:edit }

bound_backoffice_user_delete:
    path:     /delete/{user}
    defaults: { _controller: BoundBackOfficeBundle:User:delete }
