_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

_main:
    resource: routing.yml

# Redirect hostnames in route
bound_api:
    resource: "@BoundApiBundle/Resources/config/routing.yml"
    prefix: /api

bound_back_office:
    resource: "@BoundBackOfficeBundle/Resources/config/routing.yml"
    prefix: /admin

# Enable FOS Routes in Admin
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /admin

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /admin

# Enable OAuth routes in Api
hwi_oauth_service_redirect:
    path: /api/oauth/v2.0/{service}/{action}/{token}
    defaults: { _controller: BoundCoreBundle:Provider:redirectToService, token: null }

hwi_oauth_service_back:
    path: /api/oauth/v2.0/back
    defaults: { _controller: BoundCoreBundle:Provider:backFromService }

hwi_oauth_check_facebook:
    path: /api/oauth/v2.0/check-facebook

hwi_oauth_check_twitter:
    path: /api/oauth/v2.0/check-twitter
