bound_api:
    resource: "@BoundApiBundle/Resources/config/routing.yml"
    host: api.bound-app.com
    prefix:   /

bound_back_office:
    resource: "@BoundBackOfficeBundle/Resources/config/routing.yml"
    host: admin.bound-app.com
    prefix:   /

app:
    resource: "@BoundCoreBundle/Controller/"
    type:     annotation


#FOSRoutes
fos_user_registration_check_email:
    path:     /check-email
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }

fos_user_registration_confirm:
    path:     /confirm/{token}
    defaults: { _controller: FOSUserBundle:Registration:confirm }

fos_user_registration_confirmed:
    path:     /confirmed
    defaults: { _controller: FOSUserBundle:Registration:confirmed }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    host: admin.bound-app.com

#NelmioDocumentation
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

#HWIOAuthRoutes
hwi_oauth_service_redirect:
    path: /oauth/v2.0/login/{service}/{action}/{token}
    defaults: { _controller: BoundCoreBundle:Provider:redirectToService, action: null, token: null }

hwi_oauth_service_back:
    path: /ouath/v2.0/back
    defaults: { _controller: BoundCoreBundle:Provider:backFromService }
