bound_back_office:
    resource: "@BoundBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admin

bound_api:
    resource: "@BoundApiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@BoundBackOfficeBundle/Controller/"
    type:     annotation


#FOSRoutes
fos_user_registration_check_email:
    path:     /check-email
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }

fos_user_registration_confirm:
    path:     /confirm/{token}
    defaults: { _controller: FOSUserBundle:Registration:confirm }

fos_user_registration_confirmed:
    path:     /confirmed
    defaults: { _controller: FOSUserBundle:Registration:confirmed }

fos_user_security_logout:
    path:     /logout
    defaults: { _controller: FOSUserBundle:Registration:confirmed }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting


#HWIOAuthRoutes
hwi_oauth_service_redirect:
    path: /login/{service}/{token}
    defaults: { _controller: BoundCoreBundle:Provider:redirectToService, token: null }

# hwi_oauth_redirect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#     prefix:   /login

# hwi_oauth_connect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#     prefix: /login

# hwi_oauth_security:
#     resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#     prefix:   /login

# facebook_login:
#     path: /login/check-facebook
#     defaults: { _controller: BoundCoreBundle:Security:facebook }
