# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        hwi:
            id: hwi_oauth.user.provider

    firewalls:
        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                login_path: /login
                use_forward: false
                failure_path: /login

                oauth_user_provider:
                    service: my_user_provider
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                check_path: /login_check
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
