# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        hwi:
            id: hwi_oauth.user.provider

    firewalls:
        api:
            host: api.bound-app.com
            anonymous: ~
            oauth:
                resource_owners:
                    facebook: "/oauth/v2.0/login/check-facebook"
                use_forward: false
                login_path: hwi_oauth_service_back
                failure_path: hwi_oauth_service_back
                default_target_path: hwi_oauth_service_back

                oauth_user_provider:
                    service: my_user_provider

        admin:
            host: admin.bound-app.com
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY, host: admin.bound-app.com }
        - { path: ^/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY, host: admin.bound-app.com }
        - { path: ^/, role: ROLE_ADMIN, host: admin.bound-app.com }

        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
