services:
    my_user_provider:
        class: Bound\CoreBundle\Provider\FOSUBUserProvider
        arguments: [ @service_container, @doctrine.orm.entity_manager, @fos_user.user_manager, {facebook: facebook_id, twitter: twitter_id, instagram: instagram_id, linkedin: linkedin_id, strava: strava_id, deezer: deezer_id} ]
