<?php

namespace Bound\CoreBundle\Entity;

/**
 * FriendRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
