<?php

namespace Bound\CoreBundle\Entity;

use Bound\CoreBundle\Entity\Player;

/**
 * FriendRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendRequestRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllRequests(Player $player) {
        $qb = $this->createQueryBuilder('r');

        $qb->where('r.from = :player');
        $qb->orWhere('r.to = :player');
        $qb->setParameter(':player', $player);

        return $qb->getQuery()->getResult();
    }
}
