bound_api_achievement_all:
    path:     /all
    defaults: { _controller: BoundApiBundle:Achievement:all }

bound_api_achievement_get:
    path:     /get/{salt}
    defaults: { _controller: BoundApiBundle:Achievement:get }
