bound_api_achievement_all:
    path:     /all
    defaults: { _controller: BoundApiBundle:Achievement:all }

bound_api_achievement_get:
    path:     /get/{slug}
    defaults: { _controller: BoundApiBundle:Achievement:get }

bound_api_achievement_create:
    path:     /create
    defaults: { _controller: BoundApiBundle:Achievement:post }

bound_api_achievement_modify:
    path:     /modify/{slug}
    defaults: { _controller: BoundApiBundle:Achievement:put }

bound_api_achievement_delete:
    path:     /delete/{slug}
    defaults: { _controller: BoundApiBundle:Achievement:delete }
