bound_api_user:
    type: rest
    resource: "Bound\ApiBundle\Controller\UserController"

bound_api_achievement:
    type: rest
    resource: "Bound\ApiBundle\Controller\AchievementController"

bound_api_crew:
    type: rest
    resource: "Bound\ApiBundle\Controller\CrewController"
